spring:
  jpa:
    database: h2
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:~/meuslivros;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver