CREATE TABLE categoria (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(200) NOT NULL
)  ENGINE=INNODB;

CREATE TABLE livro (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(200) NOT NULL,
    autor VARCHAR(200) NOT NULL,
    categoria_id INT NOT NULL,
    FOREIGN KEY (categoria_id) REFERENCES categoria(id)
)  ENGINE=INNODB;

CREATE TABLE usuario (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(200) NOT NULL,
  username VARCHAR(20) NOT NULL,
  password VARCHAR(200) NOT NULL
)  ENGINE=INNODB;

CREATE TABLE permissao (
	id INT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	descricao VARCHAR(50)
)  ENGINE=INNODB;

CREATE TABLE usuario_permissao (
	usuario_id INT NOT NULL,
	permissao_id INT NOT NULL,
	FOREIGN KEY (usuario_id) REFERENCES usuario(id),
	FOREIGN KEY (permissao_id) REFERENCES permissao(id)
)  ENGINE=INNODB;